import Foundation
import Testing

@testable import LitmusCore

@Suite("Generated files")
struct GeneratedFilesTests {
    /// A project in a folder of its repository, as a Tuist app's modules are.
    private func repository() throws -> (repo: URL, project: URL) {
        let repo = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("litmus-generated-\(UUID().uuidString)")
        let project = repo.appendingPathComponent("App")
        try FileManager.default.createDirectory(at: project.appendingPathComponent("Derived/Sources"), withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: project.appendingPathComponent("Sources"), withIntermediateDirectories: true)
        return (repo, project)
    }

    private func git(_ arguments: String..., in repo: URL) throws {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
        process.arguments = ["-c", "user.name=t", "-c", "user.email=t@t"] + arguments
        process.currentDirectoryURL = repo
        process.standardOutput = FileHandle.nullDevice
        process.standardError = FileHandle.nullDevice
        try process.run()
        process.waitUntilExit()
    }

    @Test("leaves out what git ignores, marks generated, or a tool signed")
    func generated() throws {
        let (repo, project) = try repository()
        defer { try? FileManager.default.removeItem(at: repo) }

        let files = [
            "Derived/Sources/TuistBundle+App.swift": "private class BundleFinder {}\n",
            "Sources/Strings.swift": "// swiftlint:disable all\n// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen\n\nenum L10n {}\n",
            "Sources/Model.pb.swift": "// DO NOT EDIT.\n// swift-format-ignore-file\nstruct Model {}\n",
            "Sources/API.swift": "struct API {}\n",
            "Sources/Feed.swift": "//\n//  Feed.swift\n//  Created by someone.\n//\n\nstruct Feed { let note = \"generated by the server\" }\n",
            "Sources/Kept.swift": "struct Kept {}\n",
        ]
        try "Derived/\n".write(to: project.appendingPathComponent(".gitignore"), atomically: true, encoding: .utf8)
        try "Sources/API.swift linguist-generated=true\n".write(to: project.appendingPathComponent(".gitattributes"), atomically: true, encoding: .utf8)
        for (path, text) in files {
            try text.write(to: project.appendingPathComponent(path), atomically: true, encoding: .utf8)
        }
        try git("init", "-q", in: repo)

        let generated = GeneratedFiles.among(Array(files.keys), in: project)

        #expect(generated == [
            "Derived/Sources/TuistBundle+App.swift", "Sources/Strings.swift", "Sources/Model.pb.swift", "Sources/API.swift",
        ])
    }

    /// Without a repository there is no .gitignore to read, and the comment
    /// is all there is.
    @Test("reads only the comment outside a repository")
    func outsideRepository() throws {
        let (repo, project) = try repository()
        defer { try? FileManager.default.removeItem(at: repo) }

        try "Derived/\n".write(to: project.appendingPathComponent(".gitignore"), atomically: true, encoding: .utf8)
        try "// @generated\nstruct A {}\n".write(to: project.appendingPathComponent("Sources/A.swift"), atomically: true, encoding: .utf8)
        try "struct B {}\n".write(to: project.appendingPathComponent("Derived/Sources/B.swift"), atomically: true, encoding: .utf8)

        let generated = GeneratedFiles.among(["Sources/A.swift", "Derived/Sources/B.swift"], in: project)

        #expect(generated == ["Sources/A.swift"])
    }

    /// A tracked file is someone's, whatever .gitignore came to say later.
    @Test("keeps a file git tracks though .gitignore names it")
    func tracked() throws {
        let (repo, project) = try repository()
        defer { try? FileManager.default.removeItem(at: repo) }

        try "struct B {}\n".write(to: project.appendingPathComponent("Derived/Sources/B.swift"), atomically: true, encoding: .utf8)
        try git("init", "-q", in: repo)
        // Forced: a global excludes file may already ignore Derived/.
        try git("add", "-f", "App/Derived/Sources/B.swift", in: repo)
        try git("commit", "-q", "-m", "base", in: repo)
        try "Derived/\n".write(to: project.appendingPathComponent(".gitignore"), atomically: true, encoding: .utf8)

        #expect(GeneratedFiles.among(["Derived/Sources/B.swift"], in: project).isEmpty)
    }
}
